MyProject/actors/urls.py
from django.urls import path

from MyProject.actors.views import ActorsListView, actor_details

urlpatterns = (path('', ActorsListView.as_view(), name='list of actors'),
               path('details/<int:actor_id>/', actor_details, name='actor details'),
               )

MyProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyProject.common.urls')),
    path('accounts/',  include('MyProject.accounts.urls')),
    path('movies/', include('MyProject.movies.urls')),
    path('actors/', include('MyProject.actors.urls')),
    path('data/', include('MyProject.data.urls')),
]

MyProject/actors/models.py
from django.db import models

from MyProject.settings import TMDB_IMAGE_PATH


class Actor(models.Model):
    name = models.CharField(
        max_length=150,
        blank=False,
        null=False
    )
    biography = models.TextField(
        blank=False,
        null=False
    )
    birthday = models.CharField(
        max_length=30,
        blank=False,
        null=False,
    )
    deathday = models.CharField(
        max_length=30,
        blank=False,
        null=False,
    )
    place_of_birth = models.CharField(
        max_length=100,
        blank=False,
        null=False,
    )

    profile_path = models.URLField(blank=False, null=False)
    tmdb_id = models.IntegerField(blank=False, null=False)

    def __str__(self):
        return self.name

    def movie_image(self):
        return f"{TMDB_IMAGE_PATH}{self.profile_path}"

MyProject/actors/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import generic as views

from MyProject.actors.models import Actor


class ActorsListView(LoginRequiredMixin, views.ListView):
    redirect_field_name = 'nextpage'
    queryset = Actor.objects.order_by('?')[:20]
    template_name = 'actors/list-actors.html'




def actor_details(request, actor_id):
    actor = Actor.objects.get(id=actor_id)
    context = {
        'actor': actor,
    }
    return render(request, 'actors/actor-details.html', context)

templates/actors/actor-details.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
    <article>

      <section class="movie-detail">
        <div class="container">

          <figure class="movie-detail-banner">

            <img src="{{ actor.movie_image }}" alt="{{ actor.name}}">

          </figure>

          <div class="movie-detail-content">

            <h1 class="h1 detail-title">
                <strong>{{ actor.name }}</strong>
            </h1>
              <h1 class="h3">
                  Biography</h1>

            <p class="storyline">
                {{ actor.biography }}
            </p>
              <h3 class="h3 detail-title">
                  Birthday {{ actor.birthday }}
              </h3>
          </div>

        </div>
      </section>

    </article>
{% endblock %}

templates/actors/import-actors.html
<h1>You are successfully adding your ACTORS</h1>

templates/actors/list-actors.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
    <article>
        <!--
          - #ACTORS
        -->

        <section class="actors">
            <div class="container">

                <p class="section-subtitle"></p>

                <h2 class="h2 section-title">Popular Actors</h2>

                <ul class="movies-list">
                    {% for actor in actor_list %}
                    <li>
                        <div class="movie-card">

                            <a href="{% url 'actor details' actor_id=actor.id %}">
                                <figure class="card-banner">
                                    <img src="{{ actor.movie_image }}" alt="{{ actor.name}}">
                                </figure>
                            </a>

                            <div class="title-wrapper">
                                <a href="{% url 'actor details' actor_id=actor.id %}">
                                    <h3 class="card-title">{{ actor.name}}</h3>
                                </a>

                                <time datetime="2022">{{ actor.birthday }}</time>
                            </div>

                            <div class="card-meta">
                                <div class="badge badge-outline">2K</div>

                                <div class="rating">
                                    <ion-icon name="star"></ion-icon>

                                    <data>8.6</data>
                                </div>
                            </div>

                        </div>
                    </li>
                    {% endfor %}
                </ul>

            </div>
        </section>


        <!--
          - #CTA
        -->

        <section class="cta">
            <div class="container">

                <div class="title-wrapper">
                    <h2 class="cta-title">Trial start first 30 days.</h2>

                    <p class="cta-text">
                        Enter your email to create or restart your membership.
                    </p>
                </div>

                <form action="" class="cta-form">
                    <input type="email" name="email" required placeholder="Enter your email" class="email-field">

                    <button type="submit" class="cta-form-btn">Get started</button>
                </form>

            </div>
        </section>

    </article>
{% endblock %}